version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: user_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
